apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: "{{ .Values.image.repository }}-authorization:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.authorization.port }}
          env:
            - name: PORT
              value: "{{ .Values.services.authorization.port }}"
